kind: ConfigMap
apiVersion: v1
metadata:
  name: elasticsearch-config-yc
  namespace: file-service
data:
  elasticsearch.yml: |
    cluster.name: "docker-cluster" 
    network.host: 0.0.0.0
    http.cors.allow-origin: "*"
    http.cors.enabled: true
    bootstrap.memory_lock: true
    xpack.security.transport.ssl.enabled: false
    xpack.security.enabled: true
---
apiVersion: v1
kind: Secret
metadata:
  name: elastic-secret
  namespace: file-service
type: Opaque
data:
  elastic-root-username: ZWxhc3RpYw==
  elastic-root-password: dGVzdA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yc-elasticsearch
  namespace: file-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yc-elasticsearch
  template:
    metadata:
      labels:
        app: yc-elasticsearch
    spec:
      volumes:
        - name: config
          configMap:
            name: elasticsearch-config-yc
            defaultMode: 420
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: file-search-pvc
      containers:
        - name: yc-elasticsearch
          image: es01:latest
          imagePullPolicy: Never
          # command: ["chmod 777 /usr/share/elasticsearch/data"]
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "chmod 777 /usr/share/elasticsearch/data","curl -X PUT 'http://localhost:9200/fileIndex?pretty'","curl -X POST  'http://localhost:9200/fileIndex/_mapping' -H 'Content-Type:application/json' -d {
                  'properties': {
                    'content': {
                      'type': 'text',
                      'analyzer': 'ik_max_word',
                      'search_analyzer': 'ik_max_word'
                    }
                  }}"]
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: discovery.type
              value: single-node
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-secret
                  key: elastic-root-password
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elastic-secret
                  key: elastic-root-username
          resources:
            limits:
              cpu: 250m
              memory: 1024Mi
            requests:
              cpu: 500m
              memory: 1024Mi
          volumeMounts:
            - name: config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
            # - mountPath: /usr/share/elasticsearch/data
            #   name: elasticsearch-data
            - name: elasticsearch-data #要與volumes 裡面name一樣
              mountPath: /usr/share/elasticsearch/data
---
apiVersion: v1
kind: Service
metadata:
  name: yc-elasticsearch
  namespace: file-service
spec:
  ports:
    - name: yc-elasticsearch
      protocol: TCP
      port: 9200
      targetPort: 9200
  selector:
    app: yc-elasticsearch
  type: ClusterIP
  sessionAffinity: None
