apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: file-service
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: file-service
type: Opaque
data:
  mongo-root-username: cm9vdA==
  mongo-root-password: ZXhhbXBsZQ==
  mongo-database: bWVkaWE=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongod
  namespace: file-service
spec:
  # serviceName: mongodb-service
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        # environment: test
        # replicaset: MainRepSet
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: mongodb-persistent-storage-claim
          persistentVolumeClaim:
            claimName: file-search-pvc
      containers:
        - name: mongod-container
          image: mongo_service:latest
          imagePullPolicy: Never
          resources:
            limits:
              cpu: 250m
              memory: 1024Mi
            requests:
              cpu: 500m
              memory: 1024Mi
          # livenessProbe:
          #   exec:
          #     command:
          #       - mongo
          #       - --disableImplicitSessions
          #       - --eval
          #       - "db.adminCommand('ping')"
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 6
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-database
          # command:
          #   [
          #     "mongoimport -u root -p example -d media -c token --type json --file /seeder.json --jsonArray  --authenticationDatabase admin",
          #   ]
          #  mongodb://root:example@127.0.0.1:27017/?compressors=disabled&gssapiServiceName=mongodb
          # mongoimport -u root -p example -d media -c token --type json --file /seeder.json --jsonArray  --authenticationDatabase admin
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-persistent-storage-claim
              mountPath: /data/db
  # volumeClaimTemplates:
  #   - metadata:
  #       name: mongodb-persistent-storage-claim
  #     spec:
  #       accessModes: ["ReadWriteOnce"]
  #       resources:
  #         requests:
  #           storage: 1Gi
