apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-service-pv
  namespace: file-service
spec:
  storageClassName: stardard
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/Datas"
    type: "DirectoryOrCreate"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-search-pvc
  namespace: file-service
spec:
  storageClassName: stardard
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 3Gi
